### ISSUE TITLE
Unable to use the plugin

### ISSUE THREAD

**Issue by ghost** [advantageous/marathon-deploy-plugin#1]
Hi,

Gradle 3.1. After installing it like:

```
plugins {
    id "io.advantageous.marathon" version "2.0.0"
}

marathonEnvironments {
    staging {
        marathonApi gradle.marathonURL
    }
}
```

I am getting:

`> Could not find method marathonEnvironments() for arguments`

**Comment by dan-garton-neoworks** [comment]
+1 on this .....

Any ideas?

**Comment by sailorgeoffrey** [comment]
dsl changed between v1 and 2.
I just updated the docs.
it is now:
marathon.environments {
    staging {
        marathonApi gradle.marathonURL
    }
}
